site_name: letsdiscuss
site_description: Discussion forum for everyone !!!
repo_url: https://github.com/akshays94/lets-discuss
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/akshays94">akshays94</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
