# Generated by Django 3.0.2 on 2020-02-20 18:33

from django.db import migrations, models

def create_user_meta_for_exisiting_users(apps, schema_editor):
  print('Trying to create usermeta for existing users ...')
  User = apps.get_model('users', 'User')
  UserMeta = apps.get_model('users', 'UserMeta')
  for user in User.objects.all():
    user_meta = UserMeta.objects.create(**{
      'user': user
    })
    print('User meta created', user_meta, '...')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermeta_userreputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='tagline',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.RunPython(create_user_meta_for_exisiting_users),
    ]
