# Generated by Django 3.0.2 on 2020-01-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_answer_answervote_questionvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
