# Generated by Django 3.0.2 on 2020-02-21 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userreputation_category'),
        ('qna', '0006_questionvote_reputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionvote',
            name='reputation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserReputation'),
        ),
    ]
