# Generated by Django 3.0.2 on 2020-02-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userreputation_category'),
        ('qna', '0007_auto_20200221_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='acceptor_reputation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptor_reputation', to='users.UserReputation'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answerer_reputation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answerer_reputation', to='users.UserReputation'),
        ),
        migrations.AddField(
            model_name='answer',
            name='reputation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_reputation', to='users.UserReputation'),
        ),
    ]
