# Generated by Django 3.0.2 on 2020-02-21 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userreputation_category'),
        ('qna', '0008_auto_20200221_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='reputation',
        ),
        migrations.AddField(
            model_name='answervote',
            name='reputation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_reputation', to='users.UserReputation'),
        ),
    ]
