# Generated by Django 3.0.2 on 2020-02-23 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userreputation_category'),
        ('qna', '0009_auto_20200221_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='answervote',
            name='downvote_reputation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downvote_reputation', to='users.UserReputation'),
        ),
    ]
