# Generated by Django 3.0.2 on 2020-02-24 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userreputation_category'),
        ('qna', '0011_auto_20200224_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='acceptor_reputation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acceptor_reputation', to='users.UserReputation'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answerer_reputation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answerer_reputation', to='users.UserReputation'),
        ),
        migrations.AlterField(
            model_name='questionvote',
            name='reputation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.UserReputation'),
        ),
    ]
